---
- name: Disable IPv6 tempaddr
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.use_tempaddr
    value: '0'
    reload: yes

- name: Disable IPv6 tempaddr by default
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.use_tempaddr
    value: '0'
    reload: yes

- name: Configure IPv6 Router Advertisement (RA) acceptance
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: '{{ 1 if cybera_sysctl_ipv6_accept_ra else 0 }}'
    reload: yes

- name: Configure IPv6 Router Advertisement (RA) acceptance by default
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.accept_ra
    value: '{{ 1 if cybera_sysctl_ipv6_accept_ra else 0 }}'
    reload: yes
