---
- name: Converge
  hosts: all
  tasks:
    - name: Include test data
      include_vars: vars.yml

    - name: Include ansible-cybera-common
      include_role:
        name: "ansible-cybera-common"
