---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu1804
    image: "geerlingguy/docker-ubuntu1804-ansible:latest"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp:exec
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
  # Unable to test centos at this time
  #- name: centos7
  #  image: docker.io/pycontribs/centos:7
  #  pre_build_image: true
  #  privileged: true
  #  tmpfs:
  #    - /run
  #    - /tmp:exec
  #  volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #  command: "/usr/sbin/init"
  #- name: centos8
  #  image: docker.io/pycontribs/centos:8
  #  pre_build_image: true
  #  privileged: true
  #  tmpfs:
  #    - /run
  #    - /tmp:exec
  #  volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #  command: "/usr/sbin/init"
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
