- name: Prepare
  hosts: all

  tasks:
    - name: Refresh package cache
      ansible.builtin.package:
        update_cache: yes

    - name: Install tzdata
      ansible.builtin.package:
        name: tzdata
      when: ansible_os_family == "Debian"

    - name: Create group to later remove
      ansible.builtin.group:
        name: jdoe
        gid: "1001"

    - name: Create user to later remove
      ansible.builtin.user:
        name: jdoe
        state: present
        uid: "1001"
        group: "1001"
        shell: /bin/bash
        password: '*'
        create_home: true

    - name: Ensure the sudo group exists
      ansible.builtin.group:
        name: sudo
        gid: "27"
        state: present
