- name: Prepare
  hosts: all

  tasks:
    - name: Create group to later remove
      group:
        name: jdoe
        gid: 1001

    - name: Create user to later remove
      user:
        name: jdoe
        state: present
        uid: 1001
        group: 1001
        shell: /bin/bash
        password: '*'
        create_home: true

    - name: Ensure the sudo group exists
      group:
        name: sudo
        gid: 27
        state: present
