---
# These variables are test values used for testing
# the ansible-cybera-common playbook with Molecule.
cybera_networks_ipv4_trusted_global:
  - 192.168.1.0/24

cybera_networks_ipv4_trusted:
  - 172.17.0.0/16

cybera_open_ports_ipv4:
  - tcp: 80
  - tcp: 443

cybera_open_ports_ipv6:
  - tcp: 80
  - tcp: 443

cybera_packages_debian_global:
  cron: present

cybera_packages_debian:
  curl: present
  git:  present

cybera_packages_redhat_global:
  curl:  present

cybera_packages_redhat:
  which: present

cybera_acng_server: "acng-yyc.cloud.cybera.ca"

cybera_ssh_public_keys:
  foo_key:
    state: present
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAbGlbaY0OvmEwoEX6KVwLBe9gOjiuAt6zxf2qdWMbc8Q3X2swom4xk65R9pankz0afQs2fa/oxwJO1FL61voh523EILIlDNARE8XdsoD9CVaAMlH4ibaODpUUUyOyR2wOKjuGzGICfKyUFniEWW+3ufohP4FTf/jtu8ahwAOl2iWBpWrC+Dv/gRsxx3AHbXMaJHFT30U+YnacjVTUPupMXahdCqEB16Zm5weYXa5VaFOQBFhoqbGom5BWUOhv2JZULecHJu6XNWW/6OGnijVxf3nH9/aDmEbizuj8tSxL3ZODVupt88NCeuzAOIEc6i6g7d262U+OpUmQEg1AHaA/ foo"
  bar_key:
    state: present
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDp/f92WVg0Le++GXkpGUI0Nljh/oE4JqYHpSaMi7I6nt1U2EX3zcZ9hLwoXQLpXgFzWbx1GrdZmFGQkpWEzZorN6D+xpNPxVdT7KhgTrmyC/jlEGSME3qV41i5XGeH4Yjr7rkCnNmlwZ73shqbruyZTnEFQsqN2HwSHb91x5cH5I6/BohSvxxmEnMMXtPM4HLY6bXG+KdRc29Kh5k54LJIV6yCO7Y1B7/GpAgy5fy+dAJN0cDrN6jDEQKTxLKxZRkh3YhN2OviZpwz47HtlSYkHmRlcX3uXKdxcvoLIS8X//15hE7v8ZfiEH2sNd0SZVyEKdYrgmiq6Fhd5PiRQDHL bar"

cybera_ssh_authorized_keys_global:
  root:
    user: 'root'
    ssh_keys: ['foo_key']

cybera_ssh_authorized_keys:
  root:
    user: 'root'
    ssh_keys: ['bar_key']
  foo:
    user: 'foo'
    ssh_keys: ['foo_key']

cybera_system_users_absent:
  - jdoe

cybera_system_users:
  foo:
    state: present
    uid: 1001
    gid: 1001
    shell: /bin/bash
    password: '*'
    create_home: true

  bar:
    state: present
    uid: 1002
    gid: 1002
    shell: /bin/bash
    password: '*'
    home: /opt/bar
    create_home: true

cybera_rsyslog_ssl_ca_file: /etc/ssl/certs/rsyslog.crt
cybera_rsyslog_upstream_server: localhost

cybera_postfix_relayhost: example.com
cybera_mail_aliases_global:
  root:
    - john.doe@example.com
    - jane.doe@example.com

cybera_mail_aliases:
  root:
    - jack.doe@example.com
