---
# These variables are test values used for testing
# the ansible-cybera-common playbook with Molecule.
cybera_networks_ipv4_trusted:
  - 172.17.0.0/16

cybera_packages_debian:
  cron: present
  curl: present
  git:  present

cybera_packages_redhat:
  curl:  present
  which: present

cybera_acng_server: "acng-yyc.cloud.cybera.ca"

cybera_ssh_public_keys:
  joe:
    state: present
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHkA8jnZOoJM6Qw/IkcjOlKJ63CARlV0TQ9QsJEe47Bh5u7o1hDN2RXygnB7FHbKkDJaG/XaUHCQ7NMB4kEDtyeFmHhLKD661YF3IFbrQiW9pKNMC4AbUPDJBgBVctLj98hZg/GJLX/NrLQHAL3n7jhgNHZ9k1dNBGkZSSOBv38mGI8Ro8WlpMorYGLhxdz8cu3r/v36giVbBf2sCF79+CHJDSJnmO6yJ5K3K44SX3+IWcRB+pxm6OJXLXiwvE7mFkxVyuQHR1XrMHNC8hE5Vdf05RwRqyNm3j0by2upmBevvJasLE54M3OJiNxwhyhMqe9JIhBCUxENZYz337ZIsD jtopjian"

cybera_ssh_authorized_keys:
  - user: root
    ssh_keys: ['joe']
  - user: joe
    ssh_keys: ['joe']

cybera_system_users:
  joe:
    state: present
    uid: 1001
    gid: 1001
    shell: /bin/bash
    password: '*'
    create_home: true
