---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Include test data
      ansible.builtin.include_vars: vars.yml

    # Confirm SSH keys
    - name: Get SSH authorized_keys file
      ansible.builtin.command:
        cmd: "cat /root/.ssh/authorized_keys"
      register: authorized_keys_output
      changed_when: false

    - name: Verify SSH keys are installed
      ansible.builtin.assert:
        that:
          - "'foo' in authorized_keys_output.stdout"
          - "'bar' in authorized_keys_output.stdout"

    # Confirm iptables rules
    - name: List iptables rules
      ansible.builtin.command:
        cmd: "iptables-save"
      register: iptables_save_output
      changed_when: false

    - name: Verify iptables networks are configured correctly
      ansible.builtin.assert:
        that:
          - "'{{ item }} -j ACCEPT' in iptables_save_output.stdout"
      loop: "{{ cybera_networks_ipv4_trusted_global | zip(cybera_networks_ipv4_trusted) | flatten }}"

    - name: Verify iptables ports configured correctly
      ansible.builtin.assert:
        that:
          - "'--dport {{ (item|dict2items).0.value }} -j ACCEPT' in iptables_save_output.stdout"
      loop: "{{ cybera_open_ports_ipv4 }}"

    # Confirm package installation
    - name: List curl package
      ansible.builtin.command:
        cmd: which curl
      register: curl_output
      changed_when: false

    - name: Verify curl is correctly installed
      ansible.builtin.assert:
        that:
          - "'curl' in curl_output.stdout"

    # Confirm acng
    - name: Get acng file contents
      ansible.builtin.command:
        cmd: "cat /etc/apt/apt.conf.d/01apt-cacher-ng-proxy"
      register: acng_output
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Verify acng is configured correctly
      ansible.builtin.assert:
        that:
          - "'Acquire::http { Proxy \"http://acng-yyc.cloud.cybera.ca:3142\"; };' in acng_output.stdout"
      when: ansible_os_family == "Debian"

    # Confirm dotfiles
    - name: Check if tmux.conf.mcjones exists
      ansible.builtin.command:
        cmd: "ls -l /root/.tmux.conf.mcjones"
      register: dotfiles_output
      changed_when: false

    - name: Verify dotfiles was setup
      ansible.builtin.assert:
        that:
          - "'cybera-dotfiles' in dotfiles_output.stdout"

    # Confirm IPv6 sysctl settings
    - name: Get sysctl.conf contents
      ansible.builtin.command:
        cmd: "sysctl -a"
      register: sysctl_output
      changed_when: false

    - name: Verify IPv6 sysctl settings
      ansible.builtin.assert:
        that:
          - "'net.ipv6.conf.all.use_tempaddr = 0' in sysctl_output.stdout"
          - "'net.ipv6.conf.all.accept_ra = 1' in sysctl_output.stdout"

    # Verify Ubuntu quirks
    - name: Check for removed files
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - "/etc/cron.weekly/update-notifier-common"
        - "/etc/cron.daily/mlocate"
        - "/etc/cron.monthly/ieee-data"
        - "/etc/cron.d/mdadm"
        - "/etc/apt/apt.conf.d/20auto-upgrades.ucf-dist"
      register: removed_files_stat

    - name: Verify files are removed
      ansible.builtin.assert:
        that:
          - "'{{ item.stat.exists }}' == 'False'"
      loop: "{{ removed_files_stat.results }}"

    # Verify users were removed
    - name: Get contents of /etc/group
      ansible.builtin.command:
        cmd: "cat /etc/group"
      register: etc_group_output
      changed_when: false

    - name: Get contents of /etc/passwd
      ansible.builtin.command:
        cmd: "cat /etc/passwd"
      register: etc_passwd_output
      changed_when: false

    - name: Verify jdoe user does not exist
      ansible.builtin.assert:
        that:
          - "'jdoe' not in etc_group_output.stdout"
          - "'jdoe' not in etc_passwd_output.stdout"

    # Verify users exist
    - name: Check for foo home directory
      ansible.builtin.stat:
        path: "/home/foo"
      register: user_foo_stats

    - name: Verify foo user exist
      ansible.builtin.assert:
        that:
          - "'{{ user_foo_stats.stat.exists }}' == 'True'"

    - name: Get user's groups
      ansible.builtin.command:
        cmd: "groups foo"
      register: user_foo_groups
      changed_when: false

    - name: Verify user's groups
      ansible.builtin.assert:
        that:
          - "'sudo' in user_foo_groups.stdout"

    - name: Check for bar home directory
      ansible.builtin.stat:
        path: "/opt/bar"
      register: user_bar_stats

    - name: Verify bar user exist
      ansible.builtin.assert:
        that:
          - "'{{ user_bar_stats.stat.exists }}' == 'True'"

    - name: Get sudo file
      ansible.builtin.command:
        cmd: "cat /etc/sudoers.d/foo"
      register: sudoers_file
      changed_when: false

    - name: Verify sudo access
      ansible.builtin.assert:
        that:
          - "'foo ALL' in sudoers_file.stdout"

    - name: Capture rsyslog client.conf file
      ansible.builtin.command:
        cmd: "cat /etc/rsyslog.d/client.conf"
      register: rsyslog_client_conf
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Verify rsyslog client settings
      ansible.builtin.assert:
        that:
          - "'/etc/ssl/certs/rsyslog.crt' in rsyslog_client_conf.stdout"
          - "'localhost' in rsyslog_client_conf.stdout"
      when: ansible_os_family == "Debian"

    - name: Capture postfix configuration file
      ansible.builtin.command:
        cmd: "cat /etc/postfix/main.cf"
      register: postfix_main_cf
      changed_when: false

    - name: Verify relay host was set
      ansible.builtin.assert:
        that:
          - "'relayhost = example.com' in postfix_main_cf.stdout"

    - name: Capture mail aliases
      ansible.builtin.command:
        cmd: "cat /etc/aliases"
      register: mail_aliases
      changed_when: false

    - name: Verify mail aliases were set
      ansible.builtin.assert:
        that:
          - "'root: john.doe@example.com, jane.doe@example.com, jack.doe@example.com' in mail_aliases.stdout"
