---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Include test data
      include_vars: vars.yml

    # Confirm SSH keys
    - name: Get SSH authorized_keys file
      shell: "cat /root/.ssh/authorized_keys"
      register: authorized_keys_output

    - name: Verify SSH keys are installed
      assert:
        that:
          - "'jtopjian' in authorized_keys_output.stdout"

    # Confirm iptables rules
    - name: List iptables rules
      shell: "iptables-save"
      register: iptables_save_output

    - name: Verify iptables is configured correctly
      assert:
        that:
          - "'{{ item }} -j ACCEPT' in iptables_save_output.stdout"
      loop: "{{ cybera_networks_ipv4_trusted }}"

    # Confirm package installation
    - name: List curl package
      shell: which curl
      register: curl_output

    - name: Verify curl is correctly installed
      assert:
        that:
          - "'curl' in curl_output.stdout"

    # Confirm acng
    - name: Get acng file contents
      shell: "cat /etc/apt/apt.conf.d/01apt-cacher-ng-proxy"
      register: acng_output
      when: ansible_os_family == "Debian"

    - name: Verify acng is configured correctly
      assert:
        that:
          - "'Acquire::http { Proxy \"http://acng-yyc.cloud.cybera.ca:3142\"; };' in acng_output.stdout"
      when: ansible_os_family == "Debian"

    # Confirm dotfiles
    - name: Check if tmux.conf.mcjones exists
      shell: "ls -l /root/.tmux.conf.mcjones"
      register: dotfiles_output

    - name: Verify dotfiles was setup
      assert:
        that:
          - "'cybera-dotfiles' in dotfiles_output.stdout"

    # Confirm IPv6 sysctl settings
    - name: Get sysctl.conf contents
      shell: "sysctl -a"
      register: sysctl_output

    - name: Verify IPv6 sysctl settings
      assert:
        that:
          - "'net.ipv6.conf.all.use_tempaddr = 0' in sysctl_output.stdout"
          - "'net.ipv6.conf.all.accept_ra = 1' in sysctl_output.stdout"

    # Verify Ubuntu quirks
    - name: Check for removed files
      stat:
        path: "{{ item }}"
      loop:
        - "/etc/cron.weekly/update-notifier-common"
        - "/etc/cron.daily/mlocate"
        - "/etc/cron.monthly/ieee-data"
        - "/etc/cron.d/mdadm"
        - "/etc/apt/apt.conf.d/20auto-upgrades.ucf-dist"
      register: removed_files_stat

    - name: Verify files are removed
      assert:
        that:
          - "'{{ item.stat.exists }}' == 'False'"
      loop: "{{ removed_files_stat.results }}"

    # Verify users exist
    - name: Check for home directories
      stat:
        path: "/home/{{ item.key }}"
      loop: "{{ cybera_system_users|dict2items }}"
      register: user_stats

    - name: Verify users exist
      assert:
        that:
          - "'{{ item.stat.exists }}' == 'True'"
      loop: "{{ user_stats.results }}"
