#!/bin/sh

# NOTE: This is a customized version to install on servers
# where there is a conflict with the original netfilter-persistent
# package.

set -e

IAM=$(whoami)
PLUGINS=/usr/share/netfilter-persistent/plugins.d

if [ ${IAM} != "root" ]; then
    echo "You must be root to use this utility"
fi

# Source configuration
if [ -f "/etc/default/netfilter-persistent" ]; then
    . /etc/default/netfilter-persistent
fi

run_plugins () {
    if [ -d ${PLUGINS} ]; then
        run-parts -v -a ${1} ${PLUGINS}
    fi
}

load_rules()
{
        #load IPv4 rules
        if [ ! -f /etc/iptables/rules.v4 ]; then
                echo "Warning: skipping IPv4 (no rules to load)"
        else
                /sbin/iptables-restore < /etc/iptables/rules.v4 2> /dev/null
                if [ $? -ne 0 ]; then
                        rc=1
                fi
        fi

        #load IPv6 rules
        if [ ! -f /etc/iptables/rules.v6 ]; then
                echo "Warning: skipping IPv6 (no rules to load)"
        else
                /sbin/ip6tables-restore < /etc/iptables/rules.v6 2> /dev/null
                if [ $? -ne 0 ]; then
                        rc=1
                fi
        fi
}

save_rules()
{
        #save IPv4 rules
        #need at least iptable_filter loaded:
        /sbin/modprobe -q iptable_filter || true
        if [ ! -f /proc/net/ip_tables_names ]; then
                echo "Warning: skipping IPv4 (no modules loaded)"
        elif [ -x /sbin/iptables-save ]; then
                touch /etc/iptables/rules.v4
                chmod 0640 /etc/iptables/rules.v4
                /sbin/iptables-save > /etc/iptables/rules.v4
                if [ $? -ne 0 ]; then
                        rc=1
                fi
        fi

        #save IPv6 rules
        #need at least ip6table_filter loaded:
        /sbin/modprobe -q ip6table_filter || true
        if [ ! -f /proc/net/ip6_tables_names ]; then
                log_action_cont_msg "Warning: skipping IPv6 (no modules loaded)"
        elif [ -x /sbin/ip6tables-save ]; then
                touch /etc/iptables/rules.v6
                chmod 0640 /etc/iptables/rules.v6
                /sbin/ip6tables-save > /etc/iptables/rules.v6
                if [ $? -ne 0 ]; then
                        rc=1
                fi
        fi
}

flush_rules()
{
        if [ ! -f /proc/net/ip_tables_names ]; then
                log_action_cont_msg "Warning: skipping IPv4 (no module loaded)"
        elif [ -x /sbin/iptables ]; then
                for chain in INPUT FORWARD OUTPUT
                do
                        /sbin/iptables -P $chain ACCEPT
                done
                for param in F Z X; do /sbin/iptables -$param; done
                for table in $(cat /proc/net/ip_tables_names)
                do
                        /sbin/iptables -t $table -F
                        /sbin/iptables -t $table -Z
                        /sbin/iptables -t $table -X
                done
        fi

        if [ ! -f /proc/net/ip6_tables_names ]; then
                echo "Warning: skipping IPv6 (no module loaded)"
        elif [ -x /sbin/ip6tables ]; then
                for chain in INPUT FORWARD OUTPUT
                do
                        /sbin/ip6tables -P $chain ACCEPT
                done
                for param in F Z X; do /sbin/ip6tables -$param; done
                for table in $(cat /proc/net/ip6_tables_names)
                do
                        /sbin/ip6tables -t $table -F
                        /sbin/ip6tables -t $table -Z
                        /sbin/ip6tables -t $table -X
                done
        fi
}

case "$1" in
start|restart|reload|force-reload)
        load_rules
        ;;
save)
        save_rules
        ;;
stop)
        # Why? because if stop is used, the firewall gets flushed for a variable
        # amount of time during package upgrades, leaving the machine vulnerable
        # It's also not always desirable to flush during purge
        echo "Automatic flushing disabled, use \"flush\" instead of \"stop\""
        ;;
flush)
        flush_rules
        ;;
*)
    echo "Usage: $0 {start|restart|reload|force-reload|save|flush}" >&2
    exit 1
    ;;
esac

exit 0
